worker_processes auto;  # сколько рабочих процессов сделать. Что такое процесс?

  events {
      worker_connections 1024; # потолок соединений на один воркер
  }

  http { # что здесь означает http?
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      sendfile      on;
      keepalive_timeout 65; # сколько держать простаиваающее соединение открытым для переиспользоваания

      map $http_upgrade $connection_upgrade { # ничего не понял из объяснения.
          default upgrade;
          ''      close;
      }

      upstream chat_backend { # тоже мало что понял, типа порт пробрасывается для внешнего мира?
          server chat:8001;
      }

      server {
          listen 80; # Какой порт слушать внутри контейнера
          server_name _;

          client_max_body_size 1m; # потолок тела запроса

          location /ws/ { # некая настройка вебсокет соединений
              proxy_pass http://chat_backend;

              proxy_http_version 1.1;
              proxy_set_header Upgrade    $http_upgrade;
              proxy_set_header Connection $connection_upgrade;

              proxy_set_header Host              $host;
              proxy_set_header X-Real-IP         $remote_addr;
              proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;

              proxy_read_timeout 120s;
              proxy_send_timeout 120s;
          }

          location / {
              proxy_pass http://chat_backend;

              proxy_http_version 1.1;
              proxy_set_header Host              $host;
              proxy_set_header X-Real-IP         $remote_addr;
              proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
  }